FROM envoyproxy/envoy-dev:0b1c5aca39b8c2320501ce4b94fe34f2ad5808aa

COPY ./leaksignal.wasm /lib/leaksignal.wasm
RUN chmod go+r /lib/leaksignal.wasm
CMD /usr/local/bin/envoy -c /config/$ENVOY_YAML
# , "-l", "trace"
